name: "Caramelo Papelaria"
bio: "A papelaria mais doce que existe"
meta:
  lang: "pt_br"
  description: "A papelaria mais doce que existe"
  title: "Caramelo Papelaria"
  author: "Patterson"
  siteUrl: "https://caramelo-papelaria.github.io/"
links:
  - name: "Grupo VIP Caramelo Mimos Papelaria"
    url: "https://chat.whatsapp.com/LetX5JIw9r7KKLRKyd6qfV"
  - name: "Shopee"
    url: "https://br.shp.ee/i33i1nGv"
  - name: "Instagram"
    url: "https://www.instagram.com/caramelo.papelaria/"
  - name: "Threads"
    url: "https://www.threads.com/@caramelo.papelaria"
theme: "setembro_amarelo"
